# vi:syntax=yaml tabstop=4 expandtab
# coding: utf-8
#
# TTT proteotyping workflow snakemake configuration file
# Fredrik Boulund 2016

# Email address to send error reports to. Can be a comma-separated 
# list with several addresses.
email:
    fredrik.boulund@chalmers.se

# JSON tokenfile with OAuth2 authentication information for 
# Google Docs spreadsheet reporting.
google_token:
    /storage/TTT/code/google_token.json

# Global log level for all called scripts supporting different loglevels.
# Normally accepts DEBUG or INFO.
loglevel:
    DEBUG

# The TTT proteotyping workflow workdir.
workdir:
    /storage/TTT/

#####################################################################
# Pipeline reference data  (absolute paths)
#####################################################################
xtandem_db:
    /storage/TTT/reference_data/xtandem_refdb.fasta
blat_genome_db:
    /storage/TTT/reference_data/reference_genomes.fasta
taxref_db:
    /storage/TTT/reference_data/taxref.sqlite3
annotation_db:
    /storage/TTT/reference_data/annotation_db.sqlite3
human_proteome:
    /storage/TTT/reference_data/human_proteome.fasta
blacklist:
    /storage/TTT/reference_data/blacklist.txt
blat_resistance_db:
    /storage/TTT/reference_data/resfinder.pfa
resfinder_sqlite3_db:
    /storage/TTT/reference_data/resfinder.sqlite3


#####################################################################
# Workflow data directories  (relative to workdir)
#####################################################################
rawdir:
    0.raw
mzXMLdir:
    1.mzXML
xmldir:
    2.xml
fastadir:
    3.fasta
blast8dir:
    4.blast8
resultsdir:
    5.results


#####################################################################
# Application settings  (absolute paths)
#####################################################################
# ReAdW settings
readw_exe:
    /storage/TTT/bin/ReAdW.201510.xcalibur.exe
wineprefix:
    /storage/TTT/applications/wine32

# X! Tandem settings
xtandem_exe:
    /storage/TTT/bin/tandem.exe
xtandem_defaults:
    /storage/TTT/reference_data/default_parameters.xml
xtandem_taxonomy:
    /storage/TTT/reference_data/taxonomy.xml
xtandem_threads:
    11

# Resistance determination
resistance_min_identity:
    100.0
