# vi:syntax=yaml tabstop=4 expandtab
# encoding: utf-8
#
#  ---------------------------------------------------------- 
#  This file is part of TPARTY: http://tparty.readthedocs.org
#  ---------------------------------------------------------- 
#
#  Copyright (c) 2016, Fredrik Boulund <fredrik.boulund@chalmers.se>
#  
#  Permission to use, copy, modify, and/or distribute this software for any
#  purpose with or without fee is hereby granted, provided that the above
#  copyright notice and this permission notice appear in all copies.
#  
#  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
#  REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
#  FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
#  INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
#  LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
#  OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
#  PERFORMANCE OF THIS SOFTWARE.

# Email address to send error reports to. Can be a comma-separated 
# list with several addresses.
email:
    fredrik.boulund@chalmers.se

# JSON tokenfile with OAuth2 authentication information for 
# Google Docs spreadsheet reporting.
google_token:
    /storage/TTT/code/google_token.json

# Global log level for all called scripts supporting different loglevels.
# Normally accepts DEBUG or INFO.
loglevel:
    DEBUG

# The TTT proteotyping workflow workdir.
workdir:
    /storage/TTT/

#####################################################################
# Pipeline reference data  (absolute paths)
#####################################################################
blat_genome_db:
    /storage/TTT/reference_data/reference_genomes.fasta
taxref_db:
    /storage/TTT/reference_data/taxref.sqlite3
annotation_db:
    /storage/TTT/reference_data/annotation_db.sqlite3
human_proteome:
    /storage/TTT/reference_data/human_proteome.fasta
blacklist:
    /storage/TTT/reference_data/blacklist.txt
blat_resistance_db:
    /storage/TTT/reference_data/resfinder.pfa
resfinder_sqlite3_db:
    /storage/TTT/reference_data/resfinder.sqlite3


#####################################################################
# Workflow data directories  (relative to workdir)
#####################################################################
rawdir:
    0.raw
mzXMLdir:
    1.mzXML
xmldir:
    2.xml
fastadir:
    3.fasta
blast8dir:
    4.blast8
resultsdir:
    5.results


#####################################################################
# Application settings  (absolute paths)
#####################################################################
# ReAdW settings
readw_exe:
    /storage/TTT/bin/ReAdW.201510.xcalibur.exe
wineprefix:
    /storage/TTT/applications/wine32

# X! Tandem settings
xtandem_exe:
    /storage/TTT/bin/tandem.exe
xtandem_defaults:
    /storage/TTT/reference_data/default_parameters.xml
xtandem_taxonomy:
    /storage/TTT/reference_data/taxonomy.xml
xtandem_threads:
    11

# Resistance determination
resistance_min_identity:
    100.0
